[build]
  publish = "."
  functions = "netlify/functions"
  node_bundler = "esbuild"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  SECRETS_SCAN_OMIT_PATHS = "package-lock.json"

# Subdomain redirects for multi-domain architecture
[[redirects]]
  from = "https://tos.soltecsol.com/*"
  to = "/tos.html"
  status = 200
  force = true

[[redirects]]
  from = "https://dpa.soltecsol.com/*"
  to = "/dpa.html"
  status = 200
  force = true

[[redirects]]
  from = "https://gdpr.soltecsol.com/*"
  to = "/gdpr.html"
  status = 200
  force = true

[[redirects]]
  from = "https://helpdesk.soltecsol.com/*"
  to = "/helpdesk.html"
  status = 200
  force = true

[[redirects]]
  from = "https://plyvo.soltecsol.com/*"
  to = "/plyvo.html"
  status = 200
  force = true

[[redirects]]
  from = "https://subscriptions.soltecsol.com/*"
  to = "/subscriptions.html"
  status = 200
  force = true

[[redirects]]
  from = "https://pricing.soltecsol.com/*"
  to = "/pricing.html"
  status = 200
  force = true

[[redirects]]
  from = "https://signup.soltecsol.com/*"
  to = "/signup.html"
  status = 200
  force = true

[[redirects]]
  from = "https://login.soltecsol.com/*"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  from = "https://restriction.soltecsol.com/*"
  to = "/restriction.html"
  status = 200
  force = true

[[redirects]]
  from = "https://upgrade.soltecsol.com/*"
  to = "/upgrade.html"
  status = 200
  force = true

[[redirects]]
  from = "https://cancellation.soltecsol.com/*"
  to = "/cancellation.html"
  status = 200
  force = true

[[redirects]]
  from = "https://contact.soltecsol.com/*"
  to = "/contact.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Success page for Stripe checkout
[[redirects]]
  from = "/success"
  to = "/index.html?success=true"
  status = 200

# Cancel page for Stripe checkout
[[redirects]]
  from = "/cancel"
  to = "/index.html?cancelled=true"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API headers for CORS - Secure cross-domain authentication support
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://app.soltecsol.com, https://www.soltecsol.com, https://ai-generator.soltecsol.com, https://subscriptions.soltecsol.com, https://signup.soltecsol.com"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-CSRF-Token, X-Requested-With"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.gstatic.com https://apis.google.com https://www.paypal.com https://js.paypal.com; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://app.soltecsol.com https://subscriptions.soltecsol.com https://signup.soltecsol.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://api.openai.com https://www.paypal.com; frame-src https://www.paypal.com; object-src 'none'; base-uri 'self'; form-action 'self' https://www.paypal.com; frame-ancestors 'none'; upgrade-insecure-requests"

# Environment-specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Skip secret scanning for package-lock.json (contains dependency metadata with values matching env vars)
# SECRETS_SCAN_OMIT_PATHS is configured in the [build.environment] section above
